### ISSUE TITLE
Issue with build and push GitHub action when pushing to Orfium tools ECR

### ISSUE THREAD

**Issue by erifili117** [Orfium/orfium-github-actions#68]
Issue:

[Orfium tools ECR](719141923726.dkr.ecr.us-east-1.amazonaws.com/) uses [immutable images](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html), but the build and push action along with build local images pushes on `dev` anytime we deploy. 
https://github.com/Orfium/orfium-github-actions/blob/e89605c8221738e6b72687df301986fa830fe423/.github/workflows/build-local-images.yml#L105

Latest tag is not mutable as well https://github.com/aws/containers-roadmap/issues/878. 

This causes the action to break. We either need a new action to support this workflow or modifications on the current action to allow custom tags.

Failing build example:
https://github.com/Orfium/sso-mock-image/actions/runs/5857184281/job/15878490972 

```
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
ERROR: (*service).Write failed: rpc error: code = Canceled desc = context canceled
ERROR: failed to solve: error writing manifest blob: failed commit on ref "sha256:5c8804faa93e092ebc48647c57fd80665846c8c57f1a85cb8f71e9ccb5cd639c": unexpected status from PUT request to https://719141923726.dkr.ecr.us-east-1.amazonaws.com/v2/sso-mock-server/manifests/dev: 400 Bad Request
Error: buildx failed with: ERROR: failed to solve: error writing manifest blob: failed commit on ref "sha256:5c8804faa93e092ebc48647c57fd80665846c8c57f1a85cb8f71e9ccb5cd639c": unexpected status from PUT request to https://719141923726.dkr.ecr.us-east-1.amazonaws.com/v2/sso-mock-server/manifests/dev: 400 Bad Request
```

**Comment by vtrihos** [comment]
After discussion we concluded that we will not be using the cache feature for tools, since in most cases there will not be frequent development, which means caching will not be as useful in these cases.

We can opt-out from the caching by leaving the `BUILDX_LOCAL_CACHE_DIR` value empty.

**Comment by erifili117** [comment]
> After discussion we concluded that we will not be using the cache feature for tools, since in most cases there will not be frequent development, which means caching will not be as useful in these cases.
> 
> We can opt-out from the caching by leaving the `BUILDX_LOCAL_CACHE_DIR` value of the reusable workflow empty.

Alright perfect! I'm closing this issue.
